network:
  # ports are from the perspective of the leader
  leader_host: "127.0.0.1"
  follower_host: "127.0.0.1"
  teleop_send: 5555
  teleop_recv: 5554
  policy_host: "127.0.0.1"
  policy_send: 6554
  policy_recv: 6666
  recording: true

sync_mapping:
  scales:  [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
  offsets: [0, 0.0,  0.0,  0.0, 0, 0, 0]

leader:
  sync_pos: [0.0, -1.7, 0.0, 2.97, 0.0, 0.0, 0.0] 
  haptics:
    torque_scaling: 1.5
    minStiffness: 0.05
    maxStiffness: 1.0
    alpha: 0.35
  vertical: false

follower:
  sync_pos: [0.0, -1.7, 0.0, 2.97, 0.0, 0.0, 0.0] 
  vertical: false
