network:
  leader_host: "127.0.0.1"
  follower_host: "127.0.0.1"
  # ports are from the perspective of the leader host
  teleop_send: 5555
  teleop_recv: 5554
  policy_host: "127.0.0.1"
  # if policy.on_leader the ports are from persepctive of leader. Similar for follower
  policy_send: 6554
  # CR-DAgger will assume recieving on the below ports + 1
  policy_follower_recv: 20000
  policy_leader_recv: 10000

sync_mapping:
  scales:  [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
  offsets: [0, 0.0,  0.0,  0.0, 0, 0, 0]

policy:
  # kp: [50.0, 35.0, 25.0, 20.0, 0.0, 0.0, 0.0]
  # ki: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  # kd: [0.5, 0.5, 0.3, 0.1, 0.0, 0.0, 0.0]
  # control_signal_limit: [5, 4, 3, 2.0, 0.0, 0.0, 0.0]
  # integrator_limit: [0, 0, 0, 0, 0, 0, 0]

  kp: [140.0, 140.0, 120.0, 120.0, 5.0, 5.0, 5.0]
  ki: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  kd: [3.0, 3.0, 1.5, 0.8, 0.05, 0.05, 0.05]
  control_signal_limit: [5, 4, 3.0, 2.0, 0.9, 0.9, 0.5]
  integrator_limit: [0, 0, 0, 0, 0, 0, 0]

  # only one of these should be true. Whether leader or follower sends the data to the policy
  # NOTE: maybe kinda broken right now. policy scales are determined by the leader only
  on_leader: true
  on_follower: false

  type: "base" # one of base, cr or dg

leader:
  sync_pos: [0.0, -1.7, 0.0, 2.97, 0.0, 0.0, 0.0] 
  vertical: false

follower:
  sync_pos: [0.0, -1.7, 0.0, 2.97, 0.0, 0.0, 0.0] 
  vertical: false

gripper:
  usable: false

handle:
    torque_scaling: 1.5
    minStiffness: 0.05
    maxStiffness: 1.0
    alpha: 0.35
